### PR TITLE
kemas muhammad hanif andika

### PR DESCRIPTION
**Pull request by kemasdika**
cek server

### CODE REVIEW

**Comment by kemasdika** [comment]
env var:
SECRET_KEY
GOOGLE_CLIENT_ID

**Comment by kemasdika** [comment]
server url : https://kanbanku-c.herokuapp.com/

**Comment by kemasdika** [comment]
https://ekanbanku.web.app/

**Comment by mhmmd-ysf** [comment]
Udah bagus, Good Job!

**Pull request closed without merging**
